services:
  db:
    container_name: gem-rails.db
    image: postgres:latest
    environment:
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=psql
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/local_development/init-database:/docker-entrypoint-initdb.d/
      - db_store:/var/lib/postgresql/data
  rails:
    build:
      dockerfile: Dockerfile
    container_name: gem-rails.rails
    depends_on:
      - db
    environment:
      - BASE_URL=http://localhost:3000
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=psql
      - RAILS_ENV=development

      - BUNDLE_GEM__TEST=rspec
      - BUNDLE_GEM__CI=github
      - BUNDLE_GEM__MIT=true
      - BUNDLE_GEM__COC=true
      - BUNDLE_GEM__CHANGELOG=true
      - BUNDLE_GEM__LINTER=false
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ${PWD}:/app
      - ${PWD}/.root:/root
    # Comment platform out if not on M1?
    platform: linux/amd64
volumes:
  db_store:
